version: "3.9"

services:
  backend:
    build: ./backend
    ports:
      - "8080:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      args:
        - NEXT_PUBLIC_API_URL=https://api.energyapp.fun
        - NEXT_PUBLIC_APP_URL=https://energyapp.fun
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=https://api.energyapp.fun
      - NEXT_PUBLIC_APP_URL=https://energyapp.fun
    depends_on:
      - backend
    restart: unless-stopped
